/**
 * Auto-generate reference documentation from KAL source code.
 *
 * Usage: bun scripts/generate-docs.ts
 *
 * Generates:
 *   docs/reference/nodes.md          — Built-in node reference
 *   docs/reference/session-steps.md  — Session step type reference
 *   docs/reference/config.md         — KalConfig configuration reference
 *   docs/reference/cli.md            — CLI command reference
 *   docs/reference/hooks.md          — Hook event reference
 */

import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT = resolve(ROOT, 'docs/reference');
const CORE_SRC = resolve(ROOT, 'packages/core/src');

mkdirSync(OUT, { recursive: true });

// ── Helpers ──

function autoGenHeader(title: string, sourceFiles: string[]): string {
  const sources = sourceFiles.map((f) => `- \`${f}\``).join('\n');
  return [
    `# ${title}`,
    '',
    '> This file is auto-generated by `pnpm generate-docs`. Do not edit manually.',
    '>',
    '> Source files:',
    sources.split('\n').map((l) => '> ' + l).join('\n'),
    '',
  ].join('\n');
}

function escPipe(s: string): string {
  return s.replace(/\|/g, '\\|');
}

/** Extract the body of a named interface, handling nested braces. */
function extractInterfaceBody(src: string, name: string): string | null {
  const start = src.indexOf(`interface ${name}`);
  if (start === -1) return null;
  const braceStart = src.indexOf('{', start);
  if (braceStart === -1) return null;
  let depth = 1;
  let i = braceStart + 1;
  while (i < src.length && depth > 0) {
    if (src[i] === '{') depth++;
    else if (src[i] === '}') depth--;
    i++;
  }
  return src.slice(braceStart + 1, i - 1);
}

/** Parse TypeScript interface fields from a body string, handling types with inner semicolons. */
function parseFields(body: string): { name: string; type: string; optional: boolean }[] {
  const fields: { name: string; type: string; optional: boolean }[] = [];
  for (const line of body.split('\n')) {
    // Match field: strip trailing semicolon from the END of the line only
    const trimmed = line.trimEnd();
    if (!trimmed.endsWith(';')) continue;
    const withoutTrailingSemicolon = trimmed.slice(0, -1);
    const fieldMatch = /^\s*(\w+)(\??):\s*(.+)$/.exec(withoutTrailingSemicolon);
    if (fieldMatch) {
      fields.push({
        name: fieldMatch[1]!,
        type: fieldMatch[3]!.trim(),
        optional: fieldMatch[2] === '?',
      });
    }
  }
  return fields;
}

// ── 1. Nodes Reference ──

async function generateNodes(): Promise<void> {
  const { BUILTIN_NODES } = await import(resolve(ROOT, 'packages/core/dist/index.js'));

  const categories: Record<string, typeof BUILTIN_NODES> = {};
  for (const node of BUILTIN_NODES) {
    const cat = node.category ?? 'other';
    if (!categories[cat]) categories[cat] = [];
    categories[cat].push(node);
  }

  const categoryOrder = ['signal', 'state', 'llm', 'transform', 'utility'];
  const categoryLabels: Record<string, string> = {
    signal: 'Signal',
    state: 'State',
    llm: 'LLM',
    transform: 'Transform',
    utility: 'Utility',
  };

  let md = autoGenHeader('Built-in Nodes Reference', [
    'packages/core/src/node/builtin/*.ts',
  ]);

  // Summary table
  md += `KAL includes ${BUILTIN_NODES.length} built-in nodes across ${categoryOrder.length} categories.\n\n`;
  md += '| Node | Category | Description |\n';
  md += '|------|----------|-------------|\n';
  for (const cat of categoryOrder) {
    for (const node of categories[cat] ?? []) {
      md += `| [\`${node.type}\`](#${node.type.toLowerCase()}) | ${categoryLabels[cat] ?? cat} | ${escPipe(node.label)} |\n`;
    }
  }
  md += '\n---\n\n';

  // Detailed sections
  for (const cat of categoryOrder) {
    const nodes = categories[cat];
    if (!nodes?.length) continue;

    md += `## ${categoryLabels[cat] ?? cat} Nodes\n\n`;

    for (const node of nodes) {
      md += `### ${node.type}\n\n`;
      md += `**Label:** ${node.label}  \n`;
      md += `**Category:** ${categoryLabels[cat] ?? cat}\n\n`;

      // Inputs
      if (node.inputs.length > 0) {
        md += '**Inputs:**\n\n';
        md += '| Name | Type | Required | Default |\n';
        md += '|------|------|----------|---------|\n';
        for (const inp of node.inputs) {
          const req = inp.required ? 'Yes' : 'No';
          const def = inp.defaultValue !== undefined ? `\`${JSON.stringify(inp.defaultValue)}\`` : '—';
          md += `| \`${inp.name}\` | \`${escPipe(inp.type)}\` | ${req} | ${def} |\n`;
        }
        md += '\n';
      } else {
        md += '**Inputs:** None\n\n';
      }

      // Outputs
      if (node.outputs.length > 0) {
        md += '**Outputs:**\n\n';
        md += '| Name | Type |\n';
        md += '|------|------|\n';
        for (const out of node.outputs) {
          md += `| \`${out.name}\` | \`${escPipe(out.type)}\` |\n`;
        }
        md += '\n';
      }

      // Config
      const schema = node.configSchema;
      if (schema?.properties && Object.keys(schema.properties).length > 0) {
        md += '**Config:**\n\n';
        md += '| Property | Type | Description |\n';
        md += '|----------|------|-------------|\n';
        for (const [key, prop] of Object.entries(schema.properties) as [string, any][]) {
          const type = prop.type ?? (prop.enum ? prop.enum.join(' \\| ') : '—');
          const desc = prop.description ?? (prop.enum ? `One of: ${prop.enum.map((e: string) => `\`${e}\``).join(', ')}` : '—');
          md += `| \`${key}\` | \`${escPipe(String(type))}\` | ${escPipe(String(desc))} |\n`;
        }
        md += '\n';
      }

      // Default config
      if (node.defaultConfig && Object.keys(node.defaultConfig).length > 0) {
        md += '**Default config:**\n\n';
        md += '```json\n' + JSON.stringify(node.defaultConfig, null, 2) + '\n```\n\n';
      }

      md += '---\n\n';
    }
  }

  writeFileSync(resolve(OUT, 'nodes.md'), md);
  console.log(`  ✓ nodes.md (${BUILTIN_NODES.length} nodes)`);
}

// ── 2. Session Steps Reference ──

function generateSessionSteps(): void {
  const src = readFileSync(resolve(CORE_SRC, 'types/session.ts'), 'utf-8');

  let md = autoGenHeader('Session Step Types Reference', [
    'packages/core/src/types/session.ts',
  ]);

  md += 'The session state machine supports 6 step types. Each step has an `id` and `type` field.\n\n';

  // Parse interfaces from source
  const stepNames = ['RunFlowStep', 'PromptStep', 'BranchStep', 'ChoiceStep', 'DynamicChoiceStep', 'EndStep'];
  const steps: { name: string; fields: ReturnType<typeof parseFields> }[] = [];

  for (const name of stepNames) {
    const body = extractInterfaceBody(src, name);
    if (body) {
      steps.push({ name, fields: parseFields(body) });
    }
  }

  // Also parse the union type
  const unionMatch = /export type SessionStep\s*=\s*([^;]+);/.exec(src);
  if (unionMatch) {
    md += '```typescript\n';
    md += `type SessionStep = ${unionMatch[1]!.trim()};\n`;
    md += '```\n\n---\n\n';
  }

  for (const step of steps) {
    md += `## ${step.name}\n\n`;

    // Extract the type literal
    const typeField = step.fields.find((f) => f.name === 'type');
    if (typeField) {
      md += `**Type literal:** \`${typeField.type}\`\n\n`;
    }

    md += '| Field | Type | Required |\n';
    md += '|-------|------|----------|\n';
    for (const field of step.fields) {
      md += `| \`${field.name}\` | \`${escPipe(field.type)}\` | ${field.optional ? 'No' : 'Yes'} |\n`;
    }
    md += '\n---\n\n';
  }

  // Also document BranchCondition and DynamicChoiceOption
  for (const helperName of ['BranchCondition', 'DynamicChoiceOption']) {
    const body = extractInterfaceBody(src, helperName);
    if (!body) continue;
    const fields = parseFields(body);
    md += `## ${helperName}\n\n`;
    md += '| Field | Type | Required |\n';
    md += '|-------|------|----------|\n';
    for (const field of fields) {
      md += `| \`${field.name}\` | \`${escPipe(field.type)}\` | ${field.optional ? 'No' : 'Yes'} |\n`;
    }
    md += '\n---\n\n';
  }

  // SessionDefinition
  const sessionDefBody = extractInterfaceBody(src, 'SessionDefinition');
  if (sessionDefBody) {
    const fields = parseFields(sessionDefBody);
    md += '## SessionDefinition\n\n';
    md += '| Field | Type | Required |\n';
    md += '|-------|------|----------|\n';
    for (const field of fields) {
      md += `| \`${field.name}\` | \`${escPipe(field.type)}\` | ${field.optional ? 'No' : 'Yes'} |\n`;
    }
    md += '\n';
  }

  writeFileSync(resolve(OUT, 'session-steps.md'), md);
  console.log(`  ✓ session-steps.md (${steps.length} step types)`);
}

// ── 3. Config Reference ──

function generateConfig(): void {
  const src = readFileSync(resolve(CORE_SRC, 'types/types.ts'), 'utf-8');

  let md = autoGenHeader('Configuration Reference', [
    'packages/core/src/types/types.ts',
  ]);

  // Parse config-related interfaces
  const configInterfaces = [
    'KalConfig', 'EngineConfig', 'LLMConfig', 'ImageConfig', 'RetryConfig', 'CacheConfig',
  ];

  for (const name of configInterfaces) {
    const regex = new RegExp(`export interface ${name}\\s*\\{([^}]+)\\}`, 's');
    const match = regex.exec(src);
    if (!match) continue;

    const fields = parseFields(match[1]!);
    md += `## ${name}\n\n`;
    md += '| Field | Type | Required |\n';
    md += '|-------|------|----------|\n';
    for (const field of fields) {
      md += `| \`${field.name}\` | \`${escPipe(field.type)}\` | ${field.optional ? 'No' : 'Yes'} |\n`;
    }
    md += '\n';
  }

  // Default values
  const defaultRetryMatch = /export const DEFAULT_RETRY_CONFIG[^{]*(\{[^}]+\})/s.exec(src);
  const defaultCacheMatch = /export const DEFAULT_CACHE_CONFIG[^{]*(\{[^}]+\})/s.exec(src);

  md += '## Default Values\n\n';

  if (defaultRetryMatch) {
    md += '### DEFAULT_RETRY_CONFIG\n\n';
    md += '```json\n';
    md += '{\n';
    md += '  "maxRetries": 3,\n';
    md += '  "initialDelayMs": 1000,\n';
    md += '  "maxDelayMs": 30000,\n';
    md += '  "backoffMultiplier": 2,\n';
    md += '  "jitter": true\n';
    md += '}\n';
    md += '```\n\n';
  }

  if (defaultCacheMatch) {
    md += '### DEFAULT_CACHE_CONFIG\n\n';
    md += '```json\n';
    md += '{\n';
    md += '  "enabled": true,\n';
    md += '  "ttl": 3600000,\n';
    md += '  "maxEntries": 1000\n';
    md += '}\n';
    md += '```\n\n';
  }

  // State types
  md += '## State Types\n\n';

  const stateTypeMatch = /export type StateValueType\s*=\s*([^;]+);/.exec(src);
  if (stateTypeMatch) {
    md += `\`\`\`typescript\ntype StateValueType = ${stateTypeMatch[1]!.trim()};\n\`\`\`\n\n`;
  }

  const stateValueRegex = /export interface StateValue\s*\{([^}]+)\}/s;
  const stateValueMatch = stateValueRegex.exec(src);
  if (stateValueMatch) {
    const fields = parseFields(stateValueMatch[1]!);
    md += '### StateValue\n\n';
    md += '| Field | Type | Required |\n';
    md += '|-------|------|----------|\n';
    for (const field of fields) {
      md += `| \`${field.name}\` | \`${escPipe(field.type)}\` | ${field.optional ? 'No' : 'Yes'} |\n`;
    }
    md += '\n';
  }

  writeFileSync(resolve(OUT, 'config.md'), md);
  console.log('  ✓ config.md');
}

// ── 4. CLI Reference ──

function generateCli(): void {
  const src = readFileSync(resolve(ROOT, 'apps/engine/src/cli.ts'), 'utf-8');

  let md = autoGenHeader('CLI Command Reference', [
    'apps/engine/src/cli.ts',
  ]);

  // Extract usage lines from printUsage
  const usageMatch = /printUsage[\s\S]*?\[([^\]]+)\]\.join/s.exec(src);
  if (usageMatch) {
    const lines = usageMatch[1]!;
    // Extract string literals
    const lineRegex = /'([^']+)'/g;
    const usageLines: string[] = [];
    let lineMatch: RegExpExecArray | null;
    while ((lineMatch = lineRegex.exec(lines)) !== null) {
      usageLines.push(lineMatch[1]!);
    }

    md += '```\n' + usageLines.join('\n') + '\n```\n\n';
  }

  md += '## Commands\n\n';

  md += '### `kal serve`\n\n';
  md += 'Start the HTTP API server.\n\n';
  md += '| Option | Description | Default |\n';
  md += '|--------|-------------|---------|\n';
  md += '| `[project-path]` | Path to KAL project directory | `.` (current directory) |\n';
  md += '| `--host <host>` | Host to bind to | `127.0.0.1` |\n';
  md += '| `--port <port>` | Port to listen on | `3000` |\n\n';

  md += '### `kal play`\n\n';
  md += 'Launch the interactive TUI (terminal UI) for playing a session.\n\n';
  md += '| Option | Description | Default |\n';
  md += '|--------|-------------|---------|\n';
  md += '| `[project-path]` | Path to KAL project directory | `.` |\n\n';
  md += 'Requires `session.json` in the project.\n\n';

  md += '### `kal debug`\n\n';
  md += 'Debug session execution with state inspection.\n\n';
  md += '| Subcommand | Description |\n';
  md += '|------------|-------------|\n';
  md += '| `--start` | Start a new debug session |\n';
  md += '| `--continue [input]` | Continue an existing session with input |\n';
  md += '| `--step [input]` | Execute one step and pause |\n';
  md += '| `--state` | Print current state |\n';
  md += '| `--list` | List all debug sessions |\n';
  md += '| `--delete --run-id <id>` | Delete a debug session |\n\n';
  md += '| Option | Description |\n';
  md += '|--------|-------------|\n';
  md += '| `--force-new` | Force a new session (with `--start`) |\n';
  md += '| `--state-dir <path>` | Custom state directory |\n';
  md += '| `--run-id <id>` | Target a specific run |\n';
  md += '| `--input <input>` | Provide input value |\n';
  md += '| `--format <json\\|pretty>` | Output format |\n\n';

  md += '### `kal lint`\n\n';
  md += 'Validate project structure and configuration.\n\n';
  md += '| Option | Description | Default |\n';
  md += '|--------|-------------|---------|\n';
  md += '| `[project-path]` | Path to KAL project directory | `.` |\n';
  md += '| `--format <json\\|pretty>` | Output format | `pretty` |\n\n';

  md += '### `kal smoke`\n\n';
  md += 'Run automated smoke tests on a project.\n\n';
  md += '| Option | Description | Default |\n';
  md += '|--------|-------------|---------|\n';
  md += '| `[project-path]` | Path to KAL project directory | `.` |\n';
  md += '| `--steps N` | Number of steps to run | — |\n';
  md += '| `--input value` | Input values (repeatable) | — |\n';
  md += '| `--dry-run` | Validate without executing | — |\n';
  md += '| `--format <json\\|pretty>` | Output format | `pretty` |\n\n';

  md += '### `kal config`\n\n';
  md += 'Manage user-level configuration.\n\n';
  md += '| Subcommand | Description |\n';
  md += '|------------|-------------|\n';
  md += '| `init` | Initialize config file |\n';
  md += '| `set <key> <value>` | Set a config item |\n';
  md += '| `get <key>` | Get a config item |\n';
  md += '| `list` | List all config items |\n';
  md += '| `set-key <provider> <key>` | Securely set an API key |\n';

  writeFileSync(resolve(OUT, 'cli.md'), md);
  console.log('  ✓ cli.md');
}

// ── 5. Hooks Reference ──

function generateHooks(): void {
  const src = readFileSync(resolve(CORE_SRC, 'types/hooks.ts'), 'utf-8');

  let md = autoGenHeader('Hook Events Reference', [
    'packages/core/src/types/hooks.ts',
  ]);

  md += 'Hooks allow you to observe engine lifecycle events. Register them via the `EngineHooks` interface.\n\n';

  // Parse EngineHooks interface
  md += '## EngineHooks\n\n';
  md += '| Hook | Event Type | Level |\n';
  md += '|------|-----------|-------|\n';

  const hookRegex = /(\w+)\?\s*:\s*\(event:\s*(\w+)\)/g;
  let hookMatch: RegExpExecArray | null;
  while ((hookMatch = hookRegex.exec(src)) !== null) {
    const hookName = hookMatch[1]!;
    const eventType = hookMatch[2]!;
    let level = 'Flow';
    if (hookName.includes('Node')) level = 'Node';
    if (hookName.includes('LLM')) level = 'LLM';
    md += `| \`${hookName}\` | [\`${eventType}\`](#${eventType.toLowerCase()}) | ${level} |\n`;
  }
  md += '\n---\n\n';

  // Parse event interfaces
  const eventRegex = /export interface (\w+Event)\s*\{([^}]+)\}/gs;
  let eventMatch: RegExpExecArray | null;
  while ((eventMatch = eventRegex.exec(src)) !== null) {
    const name = eventMatch[1]!;
    const body = eventMatch[2]!;

    md += `## ${name}\n\n`;
    md += '| Field | Type |\n';
    md += '|-------|------|\n';

    for (const line of body.split('\n')) {
      const fieldMatch = /^\s*(\w+)(\??):\s*(.+);$/.exec(line.trimEnd());
      if (fieldMatch) {
        const opt = fieldMatch[2] === '?' ? ' (optional)' : '';
        md += `| \`${fieldMatch[1]}\` | \`${escPipe(fieldMatch[3]!.trim())}\`${opt} |\n`;
      }
    }
    md += '\n---\n\n';
  }

  writeFileSync(resolve(OUT, 'hooks.md'), md);
  console.log('  ✓ hooks.md');
}

// ── Main ──

async function main(): Promise<void> {
  console.log('Generating reference docs...\n');

  await generateNodes();
  generateSessionSteps();
  generateConfig();
  generateCli();
  generateHooks();

  console.log(`\nDone. Output: docs/reference/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
